export const APPLY_JOB_REQUEST = "APPLY_JOB_REQUEST";
export const APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS";
export const APPLY_JOB_FAIL = "APPLY_JOB_FAIL";
export const APPLY_JOB_ALREADY_APPLIED = "APPLY_JOB_ALREADY_APPLIED";
export const ADD_TO_JOB_APPLIED = "ADD_TO_JOB_APPLIED";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const MY_APPLIED_REQUEST = "MY_APPLIED_REQUEST";
export const MY_APPLIED_SUCCESS = "MY_APPLIED_SUCCESS";
export const MY_APPLIED_FAIL = "MY_APPLIED_FAIL";