export const APPLY_JOB_REQUEST = "APPLY_JOB_REQUEST";
export const APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS";
export const APPLY_JOB_FAIL = "APPLY_JOB_FAIL";
export const APPLY_JOB_ALREADY_APPLIED = "APPLY_JOB_ALREADY_APPLIED";
export const ADD_TO_JOB_APPLIED = "ADD_TO_JOB_APPLIED";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const MY_APPLIED_REQUEST = "MY_APPLIED_REQUEST";
export const MY_APPLIED_SUCCESS = "MY_APPLIED_SUCCESS";
export const MY_APPLIED_FAIL = "MY_APPLIED_FAIL";

export const ADMIN_ALL_APPLIED_REQUEST = "ADMIN_ALL_APPLIED_REQUEST";
export const ADMIN_ALL_APPLIED_SUCCESS = "ADMIN_ALL_APPLIED_SUCCESS";
export const ADMIN_ALL_APPLIED_FAIL = "ADMIN_ALL_APPLIED_FAIL";

export const ADMIN_UPDATE_APPLIED_REQUEST = "ADMIN_UPDATE_APPLIED_REQUEST";
export const ADMIN_UPDATE_APPLIED_SUCCESS = "ADMIN_UPDATE_APPLIED_SUCCESS";
export const ADMIN_UPDATE_APPLIED_FAIL = "ADMIN_UPDATE_APPLIED_FAIL";

export const ADMIN_DELETE_APPLIED_REQUEST = "ADMIN_DELETE_APPLIED_REQUEST";
export const ADMIN_DELETE_APPLIED_SUCCESS = "ADMIN_DELETE_APPLIED_SUCCESS";
export const ADMIN_DELETE_APPLIED_FAIL = "ADMIN_DELETE_APPLIED_FAIL";
export const ADMIN_DELETE_APPLIED_RESET = "ADMIN_DELETE_APPLIED_RESET";