export const ALL_JOB_REQUEST = "ALL_JOB_REQUEST";
export const ALL_JOB_SUCCESS = "ALL_JOB_SUCCESS";
export const ALL_JOB_FAIL = "ALL_JOB_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const JOB_DETAILS_REQUEST = "JOB_DETAILS_REQUEST";
export const JOB_DETAILS_SUCCESS = "JOB_DETAILS_SUCCESS";
export const JOB_DETAILS_FAIL = "JOB_DETAILS_FAIL";


export const CREATE_JOB_REQUEST = "CREATE_JOB_REQUEST";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_FAIL = "CREATE_JOB_FAIL";

export const ADMIN_JOB_REQUEST = "ADMIN_JOB_REQUEST";
export const ADMIN_JOB_SUCCESS = "ADMIN_JOB_SUCCESS";
export const ADMIN_JOB_FAIL = "ADMIN_JOB_FAIL";

export const ADMIN_DELETE_JOB_REQUEST = "ADMIN_DELETE_JOB_REQUEST";
export const ADMIN_DELETE_JOB_SUCCESS = "ADMIN_DELETE_JOB_SUCCESS";
export const ADMIN_DELETE_JOB_FAIL = "ADMIN_DELETE_JOB_FAIL";
export const ADMIN_DELETE_JOB_RESET = "ADMIN_DELETE_JOB_RESET";

export const ADMIN_UPDATE_JOB_REQUEST = "ADMIN_UPDATE_JOB_REQUEST";
export const ADMIN_UPDATE_JOB_SUCCESS = "ADMIN_UPDATE_JOB_SUCCESS";
export const ADMIN_UPDATE_JOB_FAIL = "ADMIN_UPDATE_JOB_FAIL";